In [1]:
%autosave 300
%reload_ext autoreload
%autoreload 2
%config Completer.use_jedi = False

Autosaving every 300 seconds

In [2]:
import os

os.chdir(
    r"/mnt/batch/tasks/shared/LS_root/mounts/clusters/insights-copilot-test/code/Users/Soutrik.Chowdhury/abi_hackathon_2k24"
)
print(os.getcwd())

/mnt/batch/tasks/shared/LS_root/mounts/clusters/insights-copilot-test/code/Users/Soutrik.Chowdhury/abi_hackathon_2k24

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)
from pandarallel import pandarallel
import re
from datetime import datetime
import gc
from sklearn.preprocessing import FunctionTransformer

# from helpers.compress import reduce_mem_usage
import pickle
import warnings
from autogluon.timeseries import TimeSeriesDataFrame, TimeSeriesPredictor
warnings.filterwarnings("ignore")

In [4]:
data_folder = "data"
macro_data_folder = "macro_data"
processed_data_folder = "processed_data_S2"
processed_macro = "macro_processed"
fe_data = "feature_engineered_data"

In [5]:
volume_monthly_df_all = pd.read_pickle(
    os.path.join(
        os.getcwd(), processed_data_folder, "all_id_vol_cluster_monthly_df.pkl"
    )
)

In [6]:
volume_monthly_df_all.shape

(79400788, 10)

In [8]:
volume_monthly_df_all.head()

,poc_ppg_id,ppg_name,unique_poc_id,year,month,sales_volume_hl_agg,year_month_start_date,sample_submission_flag,id_life_flag,poc_ppg_cluster
0,AAAA__AK_AB_CG_T,AK AB CG T,AAAA,2019,4,0.065803,2019-04-01,NaN,NaN,NaN
1,AAAA__AK_AB_CG_T,AK AB CG T,AAAA,2019,5,0.131605,2019-05-01,NaN,NaN,NaN
2,AAAA__AK_AB_CG_T,AK AB CG T,AAAA,2019,6,0.000000,2019-06-01,NaN,NaN,NaN
3,AAAA__AK_AB_CG_T,AK AB CG T,AAAA,2019,7,0.000000,2019-07-01,NaN,NaN,NaN
4,AAAA__AK_AB_CG_T,AK AB CG T,AAAA,2019,8,0.000000,2019-08-01,NaN,NaN,NaN

In [9]:
volume_monthly_df_all = volume_monthly_df_all.rename(columns={'sales_volume_hl_agg':'target'})

#### store level aggregation and store details

In [36]:
volume_monthly_df_store = volume_monthly_df_all.groupby(['unique_poc_id','year','month','year_month_start_date'],as_index=False).agg({'target':'sum'})

In [37]:
poc_atrb_df = pd.read_pickle(
    os.path.join(os.getcwd(), processed_macro, "poc_atrb_df.pkl")
)

sample_submission_df = pd.read_csv(
    os.path.join(os.getcwd(), data_folder, "sample_submission_file.csv")
)

In [38]:
volume_monthly_df_store.head()

  unique_poc_id  year  month year_month_start_date    target
0             A  2019      1            2019-01-01  0.373878
1             A  2019      2            2019-02-01  0.299103
2             A  2019      3            2019-03-01  0.249252
3             A  2019      4            2019-04-01  0.199402
4             A  2019      5            2019-05-01  0.186939

In [39]:
volume_monthly_df_store['unique_poc_id'].nunique(),volume_monthly_df_store.shape

(41646, (2293964, 5))

In [40]:
volume_monthly_df_store = volume_monthly_df_store.loc[volume_monthly_df_store['unique_poc_id'].isin(sample_submission_df['unique_poc_id'].unique())].reset_index(drop=True)

In [41]:
volume_monthly_df_store.shape,volume_monthly_df_store['unique_poc_id'].nunique()

((1201383, 5), 21387)

In [42]:
# t1 = volume_monthly_df_store.groupby(['unique_poc_id']).size()

In [43]:
# t1.max(),t1.min()

In [44]:
# poc_atrb_df.head()

In [45]:
volume_monthly_df_store = pd.merge(volume_monthly_df_store,
                                   poc_atrb_df[['unique_poc_id',"region", "subchannel", "channel_type",
                                        "sales_district","segment"]], on = ['unique_poc_id'], how='left')

In [46]:
volume_monthly_df_store.shape,volume_monthly_df_store.isnull().sum()

((1201383, 10),
 unique_poc_id            0
 year                     0
 month                    0
 year_month_start_date    0
 target                   0
 region                   0
 subchannel               0
 channel_type             0
 sales_district           0
 segment                  0
 dtype: int64)

In [47]:
test_cut_date = "2023-01-01"
full_train_df = volume_monthly_df_store.loc[volume_monthly_df_store['year_month_start_date']<test_cut_date].reset_index(drop=True)
test_df =  volume_monthly_df_store.loc[volume_monthly_df_store['year_month_start_date']>=test_cut_date].reset_index(drop=True)

In [48]:
val_date = "2022-07-01"
train_df = full_train_df.loc[full_train_df['year_month_start_date']<val_date].reset_index(drop=True)
val_df = full_train_df.loc[full_train_df['year_month_start_date']>=val_date].reset_index(drop=True)

In [49]:
train_df.shape,val_df.shape

((817539, 10), (127200, 10))

In [51]:
train_df.head(1)

,unique_poc_id,year,month,year_month_start_date,target,region,subchannel,channel_type,sales_district,segment
0,A,2019,1,2019-01-01,0.373878,ALKP,AFMJ ZQQ,KVF,TGG BIRO AFDC ADCB,AHJB ZQQ

In [52]:
train_sales_df = train_df.loc[:,['unique_poc_id','year_month_start_date','target']]
val_sales_df = val_df.loc[:,['unique_poc_id','year_month_start_date','target']]

In [264]:
# temp_ls = ['NA1__DG_CF_AF_CG_EH',
#  'NA1__CJ_CZ_CG_EH',
#  'BDMU__DG_CF_AF_CG_EH',
#  'BJBP__DG_CF_AF_CG_EH',
#  'BJAZ__CJ_DM_W_CG_T',
#  'BJAZ__DG_CF_AF_CG_EH',
#  'BJBA__CJ_CZ_CG_EH',
#  'BJBA__DG_CF_AF_CG_EH',
#  'BJBJ__DG_CF_AF_CG_EH',
#  'BJBM__ET_ES_CV',
#  'YHX__AR_EW_FM_DU_FN_DY',
#  'BJAQ__DG_CF_AF_CG_EH',
#  'BJBQ__DI_BV_FU_CE_BZ_ES_DP',
#  'BJBQ__DI_BV_FU_CE_BZ_FN_DY',
#  'BJBQ__ET_ES_CV',
#  'BJBV__CJ_CZ_CG_EH',
#  'BJBV__DG_CF_AF_CG_EH',
#  'BJAZ__CJ_CZ_CG_EH',
#  'BJAQ__CJ_CZ_CG_EH',
#  'BJBW__DG_CF_AF_CG_EH']

In [265]:
# train_sales_df = train_sales_df.loc[train_sales_df['poc_ppg_id'].isin(temp_ls)].reset_index(drop=True)
# val_sales_df = val_sales_df.loc[val_sales_df['poc_ppg_id'].isin(temp_ls)].reset_index(drop=True)

In [267]:
# train_data = TimeSeriesDataFrame.from_data_frame(
#     sales_df,
#     id_column="poc_ppg_id",
#     timestamp_column="year_month_start_date"
# )
# train_data.head()

In [268]:
# adding static features

In [55]:
static_feat = (full_train_df.drop_duplicates(['unique_poc_id'])
               [["region", "subchannel", "channel_type","sales_district","segment"]].reset_index(drop=True))
print(static_feat.shape)

(21387, 5)

In [21]:
static_feat_c = static_feat.copy()

In [22]:
train_data = TimeSeriesDataFrame.from_data_frame(
    train_sales_df,
    id_column="poc_ppg_id",
    timestamp_column="year_month_start_date",
    static_features_df = static_feat_c
    
)
train_data.head()

                              target
item_id         timestamp
AAAC__CJ_C_FN_M 2021-09-01  2.657029
                2021-10-01  1.635095
                2021-11-01  5.477568
                2021-12-01  4.905285
                2022-01-01  0.613161

In [23]:
val_data = TimeSeriesDataFrame.from_data_frame(
    val_sales_df,
    id_column="poc_ppg_id",
    timestamp_column="year_month_start_date",
    static_features_df = static_feat
    
)
val_data.head()

                              target
item_id         timestamp
AAAC__CJ_C_FN_M 2022-07-01  1.062812
                2022-08-01  2.657029
                2022-09-01  4.292124
                2022-10-01  1.635095
                2022-11-01  2.043869

In [278]:
# train_data.static_features.head()

In [25]:
predictor = TimeSeriesPredictor(prediction_length=18,freq='MS',eval_metric='SMAPE')

In [ ]:
predictor.fit(train_data,
              presets="high_quality",
            excluded_model_types=["DeepAR"],
            )

Beginning AutoGluon training...
AutoGluon will save models to 'AutogluonModels/ag-20240719_133944'
=================== System Info ===================
AutoGluon Version:  1.1.1
Python Version:     3.10.14
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #73~20.04.1-Ubuntu SMP Mon May 6 09:43:44 UTC 2024
CPU Count:          16
GPU Count:          1
Memory Avail:       63.45 GB / 108.07 GB (58.7%)
Disk Space Avail:   5036.86 GB / 5120.00 GB (98.4%)
===================================================
Setting presets to: high_quality

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': SMAPE,
 'excluded_model_types': ['DeepAR'],
 'freq': 'MS',
 'hyperparameters': 'default',
 'known_covariates_names': [],
 'num_val_windows': 1,
 'prediction_length': 18,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'target',
 'verbosity': 2}

Provided train_data has 1682426 rows, 47480 time series. Median time series length is 42 (min=1, max=42).
	Removing 12726 short time series from train_data. Only series with length >= 37 will be used for training.
	After filtering, train_data has 1450553 rows, 34754 time series. Median time series length is 42 (min=37, max=42).

Provided data contains following columns:
	target: 'target'
	static_features:
		categorical:        ['ppg_name', 'unique_poc_id', 'poc_ppg_cluster', 'category_name', 'price_segment', 'brand', ...]
		continuous (float): []

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'SMAPE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2024-07-19 13:46:19
Excluded model types: ['DeepAR']
	Found 'DeepAR' model in `hyperparameters`, but 'DeepAR' is present in `excluded_model_types` and will be removed.
Models that will be trained: ['SeasonalNaive', 'RecursiveTabular', 'DirectTabular', 'CrostonSBA', 'NPTS', 'DynamicOptimizedTheta', 'AutoETS', 'AutoARIMA', 'Chronos[base]', 'TemporalFusionTransformer', 'PatchTST']
Training timeseries model SeasonalNaive.
	-1.2898       = Validation score (-SMAPE)
	1.28    s     = Training runtime
	19.86   s     = Validation (prediction) runtime
Training timeseries model RecursiveTabular.
	Time series in the dataset are too short for chosen differences [12]. Setting differences to [1].

In [284]:
predictions = predictor.predict(train_data)
predictions.head()

data with frequency 'None' has been resampled to frequency 'MS'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble

                                      mean        0.1        0.2        0.3  \
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2022-07-01  17.358442   7.902008  11.390384  13.827571
                     2022-08-01  20.081246  10.787889  14.487692  16.968204
                     2022-09-01  17.540615   7.412927  11.547655  14.129394
                     2022-10-01  19.196789   9.403495  13.308193  15.861043
                     2022-11-01  19.310601   9.435880  13.183816  16.011727

                                       0.4        0.5        0.6        0.7  \
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2022-07-01  15.705324  17.358442  19.056426  20.755618
                     2022-08-01  18.608788  20.081246  21.725060  23.375644
                     2022-09-01  16.022554  17.540615  19.098242  20.847889
                     2022-10-01  17.696013  19.196789  20.897927  22.660767
                     2022-11-01  17.762927  19.310601  20.973966  22.944089

                                       0.8        0.9
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2022-07-01  23.276197  27.140850
                     2022-08-01  25.839374  29.429803
                     2022-09-01  23.471592  27.158672
                     2022-10-01  25.281813  29.169221
                     2022-11-01  25.717821  29.884777

In [285]:
predictions_df = predictions.reset_index(drop=False)[['item_id','timestamp','mean']]

In [286]:
predictions_df.head()

                item_id  timestamp       mean
0  BDMU__DG_CF_AF_CG_EH 2022-07-01  17.358442
1  BDMU__DG_CF_AF_CG_EH 2022-08-01  20.081246
2  BDMU__DG_CF_AF_CG_EH 2022-09-01  17.540615
3  BDMU__DG_CF_AF_CG_EH 2022-10-01  19.196789
4  BDMU__DG_CF_AF_CG_EH 2022-11-01  19.310601

In [287]:
val_data = val_data.reset_index(drop=False)[['item_id','timestamp','target']]

In [288]:
final_prediction_df = pd.merge(predictions_df,val_data, on=["item_id","timestamp"])

In [290]:
def smape(y_true, y_pred, epsilon=1e-10):
    """
    Calculate the Symmetric Mean Absolute Percentage Error (sMAPE) with handling for zero values.

    Parameters:
    - y_true: Array of true values.
    - y_pred: Array of predicted values.
    - epsilon: Small constant to avoid division by zero.

    Returns:
    - smape: The sMAPE value.
    """
    numerator = np.abs(y_pred - y_true)
    denominator = (np.abs(y_true) + np.abs(y_pred) + epsilon)
    return 100 * np.mean(2 * numerator / denominator)

In [291]:
smape(final_prediction_df['target'],final_prediction_df['mean'])

96.68151362753476

##### adding covariates

In [106]:
ppg_financials = pd.read_pickle(
    os.path.join(os.getcwd(), processed_macro, "ppg_financials.pkl")
)

calendar_df_month = pd.read_pickle(
    os.path.join(os.getcwd(), processed_macro, "calendar_df_month.pkl")
)
covid_data_monthly = pd.read_pickle(
    os.path.join(os.getcwd(), processed_macro, "covid_data_monthly.pkl")
)
weather_data_monthly = pd.read_pickle(
    os.path.join(os.getcwd(), processed_macro, "weather_data_monthly.pkl")
)

In [107]:
volume_monthly_df_best.head()

,poc_ppg_id,ppg_name,unique_poc_id,year,month,target,year_month_start_date,sample_submission_flag,id_life_flag,poc_ppg_cluster
0,AAAC__CJ_C_FN_M,CJ C FN M,AAAC,2021,9,2.657029,2021-09-01,1.0,1.0,1_1
1,AAAC__CJ_C_FN_M,CJ C FN M,AAAC,2021,10,1.635095,2021-10-01,1.0,1.0,1_1
2,AAAC__CJ_C_FN_M,CJ C FN M,AAAC,2021,11,5.477568,2021-11-01,1.0,1.0,1_1
3,AAAC__CJ_C_FN_M,CJ C FN M,AAAC,2021,12,4.905285,2021-12-01,1.0,1.0,1_1
4,AAAC__CJ_C_FN_M,CJ C FN M,AAAC,2022,1,0.613161,2022-01-01,1.0,1.0,1_1

In [123]:
volume_monthly_df_best = pd.merge(
    volume_monthly_df_best, ppg_financials, on=["ppg_name", "year", "month"], how="left"
)

In [124]:
# filling the missing values
volume_monthly_df_best["maco_hl"] = volume_monthly_df_best.groupby(["ppg_name", "month"])["maco_hl"].transform(
    lambda x: x.median()
)
volume_monthly_df_best["nr_hl"] = volume_monthly_df_best.groupby(["ppg_name", "month"])["nr_hl"].transform(
    lambda x: x.median()
)

volume_monthly_df_best.isnull().sum()

poc_ppg_id                0
ppg_name                  0
unique_poc_id             0
year                      0
month                     0
target                    0
year_month_start_date     0
sample_submission_flag    0
id_life_flag              0
poc_ppg_cluster           0
maco_hl                   0
nr_hl                     0
dtype: int64

In [125]:
calendar_df_month.head()

,year,month,quarter,year_month_start_date,holiday,month_sin,month_cos,quarter_sin,quarter_cos
0,2019,1,1,2019-01-01,1.0,0.500000,8.660254e-01,1.000000e+00,6.123234e-17
1,2019,2,1,2019-02-01,0.0,0.866025,5.000000e-01,1.000000e+00,6.123234e-17
2,2019,3,1,2019-03-01,1.0,1.000000,6.123234e-17,1.000000e+00,6.123234e-17
3,2019,4,2,2019-04-01,3.0,0.866025,-5.000000e-01,1.224647e-16,-1.000000e+00
4,2019,5,2,2019-05-01,1.0,0.500000,-8.660254e-01,1.224647e-16,-1.000000e+00

In [126]:
volume_monthly_df_best = pd.merge(
    volume_monthly_df_best,
    calendar_df_month[
        [
            "year",
            "month",
            "quarter",
            "holiday",
            "month_sin",
            "month_cos",
            "quarter_sin",
            "quarter_cos",
        ]
    ],
    on=["year", "month"],
    how="left",
)

volume_monthly_df_best.isnull().sum()

poc_ppg_id                0
ppg_name                  0
unique_poc_id             0
year                      0
month                     0
target                    0
year_month_start_date     0
sample_submission_flag    0
id_life_flag              0
poc_ppg_cluster           0
maco_hl                   0
nr_hl                     0
quarter                   0
holiday                   0
month_sin                 0
month_cos                 0
quarter_sin               0
quarter_cos               0
dtype: int64

In [127]:
# covid
volume_monthly_df_best = pd.merge(
    volume_monthly_df_best,
    covid_data_monthly[
        [
            "year",
            "month",
            "daily_cases",
            "daily_deaths",
            "daily_cases_band",
            "daily_deaths_band",
        ]
    ],
    on=["year", "month"],
    how="left",
)

# missing values
volume_monthly_df_best[["daily_cases", "daily_deaths"]] = volume_monthly_df_best[
    ["daily_cases", "daily_deaths"]
].fillna(0.0)

volume_monthly_df_best[["daily_cases_band", "daily_deaths_band"]] = (
    volume_monthly_df_best[["daily_cases_band", "daily_deaths_band"]]
    .astype(str)
    .replace("nan", "unknown")
)

volume_monthly_df_best.isnull().sum()

poc_ppg_id                0
ppg_name                  0
unique_poc_id             0
year                      0
month                     0
target                    0
year_month_start_date     0
sample_submission_flag    0
id_life_flag              0
poc_ppg_cluster           0
maco_hl                   0
nr_hl                     0
quarter                   0
holiday                   0
month_sin                 0
month_cos                 0
quarter_sin               0
quarter_cos               0
daily_cases               0
daily_deaths              0
daily_cases_band          0
daily_deaths_band         0
dtype: int64

In [128]:
# waether details
volume_monthly_df_best = pd.merge(
    volume_monthly_df_best,
    weather_data_monthly[
        [
            "year",
            "month",
            "tempmax",
            "tempmin",
            "temp",
            "dew",
            "humidity",
            "precip",
            "windgust",
        ]
    ],
    on=["year", "month"],
    how="left",
)

In [129]:
volume_monthly_df_best.head()

,poc_ppg_id,ppg_name,unique_poc_id,year,month,target,year_month_start_date,sample_submission_flag,id_life_flag,poc_ppg_cluster,maco_hl,nr_hl,quarter,holiday,month_sin,month_cos,quarter_sin,quarter_cos,daily_cases,daily_deaths,daily_cases_band,daily_deaths_band,tempmax,tempmin,temp,dew,humidity,precip,windgust
0,AAAC__CJ_C_FN_M,CJ C FN M,AAAC,2021,9,2.657029,2021-09-01,1.0,1.0,1_1,63.695448,113.044610,3,1.0,-1.000000e+00,-1.836970e-16,-1.000000e+00,-1.836970e-16,125013.0,5365.0,high,high,18.65,9.5,14.15,8.20,68.40,0.000,43.35
1,AAAC__CJ_C_FN_M,CJ C FN M,AAAC,2021,10,1.635095,2021-10-01,1.0,1.0,1_1,61.805912,111.155075,4,0.0,-8.660254e-01,5.000000e-01,-2.449294e-16,1.000000e+00,19444.0,1551.0,low,mid,22.00,13.0,17.20,10.10,68.00,0.001,44.90
2,AAAC__CJ_C_FN_M,CJ C FN M,AAAC,2021,11,5.477568,2021-11-01,1.0,1.0,1_1,62.990969,112.155744,4,0.0,-5.000000e-01,8.660254e-01,-2.449294e-16,1.000000e+00,45936.0,666.0,mid,mid,22.00,15.0,18.10,11.75,65.45,0.000,46.30
3,AAAC__CJ_C_FN_M,CJ C FN M,AAAC,2021,12,4.905285,2021-12-01,1.0,1.0,1_1,63.164604,111.637664,4,4.0,-2.449294e-16,1.000000e+00,-2.449294e-16,1.000000e+00,490234.0,1302.0,high,mid,23.00,15.8,19.30,13.20,64.50,0.000,51.50
4,AAAC__CJ_C_FN_M,CJ C FN M,AAAC,2022,1,0.613161,2022-01-01,1.0,1.0,1_1,57.546540,106.895703,1,1.0,5.000000e-01,8.660254e-01,1.000000e+00,6.123234e-17,146936.0,3948.0,high,high,27.50,17.7,22.00,15.50,64.70,0.000,41.80

In [130]:
volume_monthly_df_best.isnull().sum()

poc_ppg_id                0
ppg_name                  0
unique_poc_id             0
year                      0
month                     0
target                    0
year_month_start_date     0
sample_submission_flag    0
id_life_flag              0
poc_ppg_cluster           0
maco_hl                   0
nr_hl                     0
quarter                   0
holiday                   0
month_sin                 0
month_cos                 0
quarter_sin               0
quarter_cos               0
daily_cases               0
daily_deaths              0
daily_cases_band          0
daily_deaths_band         0
tempmax                   0
tempmin                   0
temp                      0
dew                       0
humidity                  0
precip                    0
windgust                  0
dtype: int64

In [165]:
drop_cols = ['ppg_name','unique_poc_id','sample_submission_flag',
             'id_life_flag','poc_ppg_cluster','daily_cases_band','daily_deaths_band']

In [166]:
test_cut_date = "2023-01-01"
full_train_df = volume_monthly_df_best.loc[volume_monthly_df_best['year_month_start_date']<test_cut_date].reset_index(drop=True)
test_df =  volume_monthly_df_best.loc[volume_monthly_df_best['year_month_start_date']>=test_cut_date].reset_index(drop=True)

In [167]:
val_date = "2022-07-01"
train_df = full_train_df.loc[full_train_df['year_month_start_date']<val_date].reset_index(drop=True)
val_df = full_train_df.loc[full_train_df['year_month_start_date']>=val_date].reset_index(drop=True)

In [168]:
train_df = train_df.drop(drop_cols,errors='ignore',axis=1)
val_df = val_df.drop(drop_cols,errors='ignore',axis=1)

In [169]:
train_df.shape,val_df.shape

((1682510, 22), (291424, 22))

In [170]:
# train_sales_df = train_df.loc[:,['poc_ppg_id','year_month_start_date','target']]
# val_sales_df = val_df.loc[:,['poc_ppg_id','year_month_start_date','target']]

In [179]:
temp_ls = ['NA1__DG_CF_AF_CG_EH',
 'NA1__CJ_CZ_CG_EH',
 'BDMU__DG_CF_AF_CG_EH',
 'BJBP__DG_CF_AF_CG_EH',
 'BJAZ__CJ_DM_W_CG_T',
 'BJAZ__DG_CF_AF_CG_EH',
 'BJBA__CJ_CZ_CG_EH',
 'BJBA__DG_CF_AF_CG_EH',
 'BJBJ__DG_CF_AF_CG_EH',
 'BJBM__ET_ES_CV',
 'YHX__AR_EW_FM_DU_FN_DY',
 'BJAQ__DG_CF_AF_CG_EH',
 'BJBQ__DI_BV_FU_CE_BZ_ES_DP',
 'BJBQ__DI_BV_FU_CE_BZ_FN_DY',
 'BJBQ__ET_ES_CV',
 'BJBV__CJ_CZ_CG_EH',
 'BJBV__DG_CF_AF_CG_EH',
 'BJAZ__CJ_CZ_CG_EH',
 'BJAQ__CJ_CZ_CG_EH',
 'BJBW__DG_CF_AF_CG_EH']

In [180]:
train_sales_df = train_df.loc[train_df['poc_ppg_id'].isin(temp_ls)].reset_index(drop=True)
val_sales_df = val_df.loc[val_df['poc_ppg_id'].isin(temp_ls)].reset_index(drop=True)

In [181]:
train_sales_df.shape,val_sales_df.shape

((924, 22), (132, 22))

In [182]:
# train_data = TimeSeriesDataFrame.from_data_frame(
#     sales_df,
#     id_column="poc_ppg_id",
#     timestamp_column="year_month_start_date"
# )
# train_data.head()

In [183]:
static_feat = static_feat.rename(columns={"item_id":"poc_ppg_id"})
static_feat_c = static_feat.copy()

In [184]:
static_feat_c.head()

,poc_ppg_id,ppg_name,unique_poc_id,poc_ppg_cluster,category_name,price_segment,brand,subbrand,subchannel,channel_type,segment
0,AAAC__CJ_C_FN_M,CJ C FN M,AAAC,1_1,BM,EJ CW,CJ,CJ C,AQXZ APPZ ADOT,BBOB,AZJC UIP
1,AAAC__DG_CF_AF_CG_EH,DG CF AF CG EH,AAAC,1_1,BM,BR,DG CF AF,DG CF AF,AQXZ APPZ ADOT,BBOB,AZJC UIP
2,AAAC__ET_ES_CV,ET ES CV,AAAC,1_1,BM,EJ CW,ET,ET,AQXZ APPZ ADOT,BBOB,AZJC UIP
3,AAAD__CJ_CZ_CG_EH,CJ CZ CG EH,AAAD,1_1,BM,BR,CJ,CJ CZ,AFMJ ZQQ,KVF,AHJB ZQQ
4,AAAD__DG_CF_AF_CG_EH,DG CF AF CG EH,AAAD,1_1,BM,BR,DG CF AF,DG CF AF,AFMJ ZQQ,KVF,AHJB ZQQ

In [185]:
train_data = TimeSeriesDataFrame.from_data_frame(
    train_sales_df,
    id_column="poc_ppg_id",
    timestamp_column="year_month_start_date",
    static_features_df = static_feat_c
    
)
train_data.head()

                                 year  month    target    maco_hl      nr_hl  \
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2019-01-01  2019      1  4.000499  36.443492  59.400052
                     2019-02-01  2019      2  1.495514  36.206908  58.612230
                     2019-03-01  2019      3  5.047359  34.322249  56.899726
                     2019-04-01  2019      4  3.925723  34.898039  57.475516
                     2019-05-01  2019      5  4.299602  33.723572  56.301050

                                 quarter  holiday  month_sin     month_cos  \
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2019-01-01        1      1.0   0.500000  8.660254e-01
                     2019-02-01        1      0.0   0.866025  5.000000e-01
                     2019-03-01        1      1.0   1.000000  6.123234e-17
                     2019-04-01        2      3.0   0.866025 -5.000000e-01
                     2019-05-01        2      1.0   0.500000 -8.660254e-01

                                  quarter_sin   quarter_cos  daily_cases  \
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2019-01-01  1.000000e+00  6.123234e-17          0.0
                     2019-02-01  1.000000e+00  6.123234e-17          0.0
                     2019-03-01  1.000000e+00  6.123234e-17          0.0
                     2019-04-01  1.224647e-16 -1.000000e+00          0.0
                     2019-05-01  1.224647e-16 -1.000000e+00          0.0

                                 daily_deaths  tempmax  tempmin   temp    dew  \
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2019-01-01           0.0    25.60     17.0  21.00  13.70
                     2019-02-01           0.0    27.60     17.7  21.75  15.15
                     2019-03-01           0.0    25.00     16.0  19.70  14.80
                     2019-04-01           0.0    22.85     13.0  18.00  12.25
                     2019-05-01           0.0    21.00     11.0  15.90  10.90

                                 humidity  precip  windgust
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2019-01-01     66.20   0.000     50.40
                     2019-02-01     68.60   0.000     46.95
                     2019-03-01     74.80   0.000     38.20
                     2019-04-01     72.65   0.002     36.25
                     2019-05-01     74.70   0.000     33.10

In [186]:
val_data = TimeSeriesDataFrame.from_data_frame(
    val_sales_df,
    id_column="poc_ppg_id",
    timestamp_column="year_month_start_date",
    static_features_df = static_feat
    
)
val_data.head()

                                 year  month     target    maco_hl      nr_hl  \
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2022-07-01  2022      7  24.376873  34.219421  56.453242
                     2022-08-01  2022      8  53.053349  33.957011  56.495186
                     2022-09-01  2022      9  31.929218  36.946794  62.723574
                     2022-10-01  2022     10  37.350455  39.216787  62.650534
                     2022-11-01  2022     11  36.041880  38.645131  62.338463

                                 quarter  holiday  month_sin     month_cos  \
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2022-07-01        3      0.0  -0.500000 -8.660254e-01
                     2022-08-01        3      1.0  -0.866025 -5.000000e-01
                     2022-09-01        3      1.0  -1.000000 -1.836970e-16
                     2022-10-01        4      0.0  -0.866025  5.000000e-01
                     2022-11-01        4      0.0  -0.500000  8.660254e-01

                                  quarter_sin   quarter_cos  daily_cases  \
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2022-07-01 -1.000000e+00 -1.836970e-16       9138.0
                     2022-08-01 -1.000000e+00 -1.836970e-16          0.0
                     2022-09-01 -1.000000e+00 -1.836970e-16          0.0
                     2022-10-01 -2.449294e-16  1.000000e+00          0.0
                     2022-11-01 -2.449294e-16  1.000000e+00          0.0

                                 daily_deaths  tempmax  tempmin   temp   dew  \
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2022-07-01         162.0     17.0      8.0  12.90   8.5
                     2022-08-01           0.0     16.0      9.0  12.90   8.4
                     2022-09-01           0.0     19.5     10.0  14.45   9.5
                     2022-10-01           0.0     23.0     14.0  18.00  11.7
                     2022-11-01           0.0     23.3     14.6  18.95  11.6

                                 humidity  precip  windgust
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2022-07-01     77.40  0.0040      29.5
                     2022-08-01     74.50  0.0020      30.8
                     2022-09-01     71.95  0.0025      29.8
                     2022-10-01     67.80  0.0000      42.3
                     2022-11-01     64.70  0.0000      38.0

In [190]:
known_covariates_names = [col for col in train_data.columns if col!= "target"]

In [187]:
# train_data.static_features.head()

In [237]:
predictor = TimeSeriesPredictor(prediction_length=6,freq='MS',eval_metric='SMAPE',
                                known_covariates_names=known_covariates_names)

In [238]:
predictor.fit(train_data,
              presets="high_quality",
            excluded_model_types=["DeepAR",'RecursiveTabular', 'WeightedEnsemble',"TemporalFusionTransformer"])

Beginning AutoGluon training...
AutoGluon will save models to 'AutogluonModels/ag-20240719_032202'
=================== System Info ===================
AutoGluon Version:  1.1.1
Python Version:     3.10.14
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #73~20.04.1-Ubuntu SMP Mon May 6 09:43:44 UTC 2024
CPU Count:          16
GPU Count:          1
Memory Avail:       94.97 GB / 108.07 GB (87.9%)
Disk Space Avail:   5065.41 GB / 5120.00 GB (98.9%)
===================================================
Setting presets to: high_quality

Fitting with arguments:
{'enable_ensemble': True,
 'eval_metric': SMAPE,
 'excluded_model_types': ['DeepAR',
                          'RecursiveTabular',
                          'WeightedEnsemble',
                          'TemporalFusionTransformer'],
 'freq': 'MS',
 'hyperparameters': 'default',
 'known_covariates_names': ['year',
                            'month',
                            'maco_hl',
                            'nr_hl',
                            'quarter',
                            'holiday',
                            'month_sin',
                            'month_cos',
                            'quarter_sin',
                            'quarter_cos',
                            'daily_cases',
                            'daily_deaths',
                            'tempmax',
                            'tempmin',
                            'temp',
                            'dew',
                            'humidity',
                            'precip',
                            'windgust'],
 'num_val_windows': 1,
 'prediction_length': 6,
 'quantile_levels': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9],
 'random_seed': 123,
 'refit_every_n_windows': 1,
 'refit_full': False,
 'skip_model_selection': False,
 'target': 'target',
 'verbosity': 2}

train_data with frequency 'None' has been resampled to frequency 'MS'.
Provided train_data has 840 rows, 20 time series. Median time series length is 42 (min=42, max=42).

Provided data contains following columns:
	target: 'target'
	known_covariates:
		categorical:        []
		continuous (float): ['year', 'month', 'maco_hl', 'nr_hl', 'quarter', 'holiday', ...]
	static_features:
		categorical:        ['ppg_name', 'unique_poc_id', 'poc_ppg_cluster', 'category_name', 'price_segment', 'brand', ...]
		continuous (float): []

AutoGluon will ignore following non-numeric/non-informative columns:
	ignored static_features: ['segment']

To learn how to fix incorrectly inferred types, please see documentation for TimeSeriesPredictor.fit

AutoGluon will gauge predictive performance using evaluation metric: 'SMAPE'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2024-07-19 03:22:05
Excluded model types: ['DeepAR', 'RecursiveTabular', 'WeightedEnsemble', 'TemporalFusionTransformer']
	Found 'RecursiveTabular' model in `hyperparameters`, but 'RecursiveTabular' is present in `excluded_model_types` and will be removed.
	Found 'TemporalFusionTransformer' model in `hyperparameters`, but 'TemporalFusionTransformer' is present in `excluded_model_types` and will be removed.
	Found 'DeepAR' model in `hyperparameters`, but 'DeepAR' is present in `excluded_model_types` and will be removed.
Models that will be trained: ['SeasonalNaive', 'DirectTabular', 'CrostonSBA', 'NPTS', 'DynamicOptimizedTheta', 'AutoETS', 'AutoARIMA', 'Chronos[base]', 'PatchTST']
Training timeseries model SeasonalNaive.
	-1.0892       = Validation score (-SMAPE)
	0.02    s     = Training runtime
	1.45    s     = Validation (prediction) runtime
Training timeseries model DirectTabular.
	-0.8313       = Validation score (-SMAPE)
	2.04    s     = Training runtime
	0.10    s     = Validation (prediction) runtime
Training timeseries model CrostonSBA.
	-0.8100       = Validation score (-SMAPE)
	0.02    s     = Training runtime
	6.39    s     = Validation (prediction) runtime
Training timeseries model NPTS.
	-1.0574       = Validation score (-SMAPE)
	0.02    s     = Training runtime
	0.04    s     = Validation (prediction) runtime
Training timeseries model DynamicOptimizedTheta.
	-0.8178       = Validation score (-SMAPE)
	0.02    s     = Training runtime
	13.81   s     = Validation (prediction) runtime
Training timeseries model AutoETS.
	-0.8069       = Validation score (-SMAPE)
	0.02    s     = Training runtime
	8.45    s     = Validation (prediction) runtime
Training timeseries model AutoARIMA.
	-0.9378       = Validation score (-SMAPE)
	0.02    s     = Training runtime
	9.84    s     = Validation (prediction) runtime
Training timeseries model Chronos[base].
	-1.0203       = Validation score (-SMAPE)
	0.01    s     = Training runtime
	1.75    s     = Validation (prediction) runtime
Training timeseries model PatchTST.
	-0.8527       = Validation score (-SMAPE)
	15.90   s     = Training runtime
	0.03    s     = Validation (prediction) runtime
Fitting simple weighted ensemble.
	Ensemble weights: {'AutoETS': 0.01, 'CrostonSBA': 0.34, 'DynamicOptimizedTheta': 0.43, 'PatchTST': 0.02, 'SeasonalNaive': 0.19}
	-0.7463       = Validation score (-SMAPE)
	1.00    s     = Training runtime
	30.13   s     = Validation (prediction) runtime
Training complete. Models trained: ['SeasonalNaive', 'DirectTabular', 'CrostonSBA', 'NPTS', 'DynamicOptimizedTheta', 'AutoETS', 'AutoARIMA', 'Chronos[base]', 'PatchTST', 'WeightedEnsemble']
Total runtime: 62.94 s
Best model: WeightedEnsemble
Best model score: -0.7463

In [239]:
predictor.known_covariates_names

['year',
 'month',
 'maco_hl',
 'nr_hl',
 'quarter',
 'holiday',
 'month_sin',
 'month_cos',
 'quarter_sin',
 'quarter_cos',
 'daily_cases',
 'daily_deaths',
 'tempmax',
 'tempmin',
 'temp',
 'dew',
 'humidity',
 'precip',
 'windgust']

In [240]:
from autogluon.timeseries.utils.forecast import get_forecast_horizon_index_ts_dataframe

future_index = get_forecast_horizon_index_ts_dataframe(train_data, prediction_length=6, freq="MS")
future_timestamps = future_index.get_level_values("timestamp")
known_covariates = pd.DataFrame(index=future_index)

In [241]:
known_covariates.shape, val_data.shape

((120, 0), (132, 20))

In [242]:
known_covariates = pd.merge(known_covariates,val_data[known_covariates_names],left_index=True,right_index=True)

In [243]:
known_covariates.isnull().sum()

year            0
month           0
maco_hl         0
nr_hl           0
quarter         0
holiday         0
month_sin       0
month_cos       0
quarter_sin     0
quarter_cos     0
daily_cases     0
daily_deaths    0
tempmax         0
tempmin         0
temp            0
dew             0
humidity        0
precip          0
windgust        0
dtype: int64

In [244]:
predictions = predictor.predict(train_data,  known_covariates=known_covariates)
predictions.head()

data with frequency 'None' has been resampled to frequency 'MS'.
Model not specified in predict, will default to the model with the best validation score: WeightedEnsemble

                                      mean        0.1        0.2        0.3  \
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2022-07-01  16.955840   7.529280  10.305514  12.621649
                     2022-08-01  20.524645  11.256336  14.306742  16.683364
                     2022-09-01  16.649035   6.589626  10.077078  12.524636
                     2022-10-01  19.143912   9.839942  12.892056  15.222467
                     2022-11-01  19.311994  10.346198  13.035636  15.591487

                                       0.4        0.5        0.6        0.7  \
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2022-07-01  15.360921  16.955840  18.604669  21.129386
                     2022-08-01  19.142782  20.524645  22.112406  24.583841
                     2022-09-01  15.247975  16.649035  18.097634  20.648531
                     2022-10-01  17.815907  19.143912  20.712668  23.219439
                     2022-11-01  18.001869  19.311994  20.761130  23.434567

                                       0.8        0.9
item_id              timestamp
BDMU__DG_CF_AF_CG_EH 2022-07-01  23.545723  26.774086
                     2022-08-01  26.940298  29.859282
                     2022-09-01  23.146514  26.096080
                     2022-10-01  25.631793  28.663132
                     2022-11-01  25.925316  29.118243

In [245]:
predictions_df = predictions.reset_index(drop=False)[['item_id','timestamp','mean']]

In [246]:
predictions_df.head()

                item_id  timestamp       mean
0  BDMU__DG_CF_AF_CG_EH 2022-07-01  16.955840
1  BDMU__DG_CF_AF_CG_EH 2022-08-01  20.524645
2  BDMU__DG_CF_AF_CG_EH 2022-09-01  16.649035
3  BDMU__DG_CF_AF_CG_EH 2022-10-01  19.143912
4  BDMU__DG_CF_AF_CG_EH 2022-11-01  19.311994

In [247]:
val_data = val_data.reset_index(drop=False)[['item_id','timestamp','target']]

In [248]:
final_prediction_df = pd.merge(predictions_df,val_data, on=["item_id","timestamp"], how="inner")

In [249]:
final_prediction_df

                        item_id  timestamp       mean     target
0          BDMU__DG_CF_AF_CG_EH 2022-07-01  16.955840  24.376873
1          BDMU__DG_CF_AF_CG_EH 2022-08-01  20.524645  53.053349
2          BDMU__DG_CF_AF_CG_EH 2022-09-01  16.649035  31.929218
3          BDMU__DG_CF_AF_CG_EH 2022-10-01  19.143912  37.350455
4          BDMU__DG_CF_AF_CG_EH 2022-11-01  19.311994  36.041880
5          BDMU__DG_CF_AF_CG_EH 2022-12-01  17.943394  43.145570
6             BJAQ__CJ_CZ_CG_EH 2022-07-01   5.089604   6.355933
7             BJAQ__CJ_CZ_CG_EH 2022-08-01   6.059326   7.477569
8             BJAQ__CJ_CZ_CG_EH 2022-09-01   6.981566   7.103690
9             BJAQ__CJ_CZ_CG_EH 2022-10-01   5.568391   7.739283
10            BJAQ__CJ_CZ_CG_EH 2022-11-01   4.599093   8.786143
11            BJAQ__CJ_CZ_CG_EH 2022-12-01   5.981067   2.991027
12         BJAQ__DG_CF_AF_CG_EH 2022-07-01  11.879489  20.563313
13         BJAQ__DG_CF_AF_CG_EH 2022-08-01  12.831387  12.936194
14         BJAQ__DG_CF_AF_CG_EH 2022-09-01  13.617982  18.806085
15         BJAQ__DG_CF_AF_CG_EH 2022-10-01  14.722279  25.909775
16         BJAQ__DG_CF_AF_CG_EH 2022-11-01  13.909352  35.705390
17         BJAQ__DG_CF_AF_CG_EH 2022-12-01  14.295424  36.303595
18            BJAZ__CJ_CZ_CG_EH 2022-07-01   3.948705   0.000000
19            BJAZ__CJ_CZ_CG_EH 2022-08-01   4.158394   2.878864
20            BJAZ__CJ_CZ_CG_EH 2022-09-01   4.357418   2.878864
21            BJAZ__CJ_CZ_CG_EH 2022-10-01   4.168399   0.000000
22            BJAZ__CJ_CZ_CG_EH 2022-11-01   3.239722   0.000000
23            BJAZ__CJ_CZ_CG_EH 2022-12-01   5.579357   5.757728
24           BJAZ__CJ_DM_W_CG_T 2022-07-01   0.028983   0.042866
25           BJAZ__CJ_DM_W_CG_T 2022-08-01   0.032838   0.046773
26           BJAZ__CJ_DM_W_CG_T 2022-09-01   0.030204   0.047662
27           BJAZ__CJ_DM_W_CG_T 2022-10-01   0.027344   0.042212
28           BJAZ__CJ_DM_W_CG_T 2022-11-01   0.027494   0.053113
29           BJAZ__CJ_DM_W_CG_T 2022-12-01   0.030293   0.071922
30         BJAZ__DG_CF_AF_CG_EH 2022-07-01   7.898856   0.000000
31         BJAZ__DG_CF_AF_CG_EH 2022-08-01   8.145570   8.636592
32         BJAZ__DG_CF_AF_CG_EH 2022-09-01   8.171656  11.515456
33         BJAZ__DG_CF_AF_CG_EH 2022-10-01   8.993791   9.870390
34         BJAZ__DG_CF_AF_CG_EH 2022-11-01   8.250327   0.000000
35         BJAZ__DG_CF_AF_CG_EH 2022-12-01   9.404884   5.757728
36            BJBA__CJ_CZ_CG_EH 2022-07-01   0.593168   0.000000
37            BJBA__CJ_CZ_CG_EH 2022-08-01   0.586403   0.934696
38            BJBA__CJ_CZ_CG_EH 2022-09-01   0.365622   0.112164
39            BJBA__CJ_CZ_CG_EH 2022-10-01   0.292559   2.056331
40            BJBA__CJ_CZ_CG_EH 2022-11-01   0.325861   2.504985
41            BJBA__CJ_CZ_CG_EH 2022-12-01   0.453130   1.121635
42         BJBA__DG_CF_AF_CG_EH 2022-07-01   0.760306   0.000000
43         BJBA__DG_CF_AF_CG_EH 2022-08-01   0.930908   1.308574
44         BJBA__DG_CF_AF_CG_EH 2022-09-01   0.511143   0.934696
45         BJBA__DG_CF_AF_CG_EH 2022-10-01   0.444152   2.093719
46         BJBA__DG_CF_AF_CG_EH 2022-11-01   0.522461   2.841476
47         BJBA__DG_CF_AF_CG_EH 2022-12-01   0.604147   2.392822
48         BJBJ__DG_CF_AF_CG_EH 2022-07-01   1.505156   1.532902
49         BJBJ__DG_CF_AF_CG_EH 2022-08-01   2.369705   2.280658
50         BJBJ__DG_CF_AF_CG_EH 2022-09-01   2.665231   3.439682
51         BJBJ__DG_CF_AF_CG_EH 2022-10-01   2.052990   2.916252
52         BJBJ__DG_CF_AF_CG_EH 2022-11-01   2.279010   2.243271
53         BJBJ__DG_CF_AF_CG_EH 2022-12-01   0.827799   6.468097
54               BJBM__ET_ES_CV 2022-07-01   0.724570   7.078765
55               BJBM__ET_ES_CV 2022-08-01   0.456766   0.000000
56               BJBM__ET_ES_CV 2022-09-01   0.535897   0.000000
57               BJBM__ET_ES_CV 2022-10-01   0.661766   0.000000
58               BJBM__ET_ES_CV 2022-11-01   0.876659   0.000000
59               BJBM__ET_ES_CV 2022-12-01   0.513626   0.000000
60         BJBP__DG_CF_AF_CG_EH 2022-07-01   4.232384   6.954139
61         BJBP__DG_CF_AF_CG_EH 2022-08-01   4.739790   4.748256
62         BJBP__DG_CF_AF_CG_EH 2022-09-01   7.069408   4.000499
63         BJBP__DG_CF_AF_CG_EH 2022-10-01   5.329595   2.878864
64         BJBP__DG_CF_AF_CG_EH 2022-11-01   6.183352   0.000000
65         BJBP__DG_CF_AF_CG_EH 2022-12-01   4.736648   0.000000
66   BJBQ__DI_BV_FU_CE_BZ_ES_DP 2022-07-01   0.076887   0.107422
67   BJBQ__DI_BV_FU_CE_BZ_ES_DP 2022-08-01   0.091112   0.106153
68   BJBQ__DI_BV_FU_CE_BZ_ES_DP 2022-09-01   0.089001   0.072720
69   BJBQ__DI_BV_FU_CE_BZ_ES_DP 2022-10-01   0.086021   0.122224
70   BJBQ__DI_BV_FU_CE_BZ_ES_DP 2022-11-01   0.094763   0.229294
71   BJBQ__DI_BV_FU_CE_BZ_ES_DP 2022-12-01   0.110678   0.276145
72   BJBQ__DI_BV_FU_CE_BZ_FN_DY 2022-07-01   0.076887   0.107422
73   BJBQ__DI_BV_FU_CE_BZ_FN_DY 2022-08-01   0.091112   0.106153
74   BJBQ__DI_BV_FU_CE_BZ_FN_DY 2022-09-01   0.089001   0.072720
75   BJBQ__DI_BV_FU_CE_BZ_FN_DY 2022-10-01   0.086021   0.122224
76   BJBQ__DI_BV_FU_CE_BZ_FN_DY 2022-11-01   0.094763   0.229294
77   BJBQ__DI_BV_FU_CE_BZ_FN_DY 2022-12-01   0.110678   0.276145
78               BJBQ__ET_ES_CV 2022-07-01   1.520270   0.000000
79               BJBQ__ET_ES_CV 2022-08-01   1.153670   0.000000
80               BJBQ__ET_ES_CV 2022-09-01   1.371139   5.875375
81               BJBQ__ET_ES_CV 2022-10-01   1.172462   8.919244
82               BJBQ__ET_ES_CV 2022-11-01   1.370919   5.946163
83               BJBQ__ET_ES_CV 2022-12-01   1.502958  10.405784
84            BJBV__CJ_CZ_CG_EH 2022-07-01   2.387892   2.243271
85            BJBV__CJ_CZ_CG_EH 2022-08-01   2.613024   2.878864
86            BJBV__CJ_CZ_CG_EH 2022-09-01   2.385653   0.000000
87            BJBV__CJ_CZ_CG_EH 2022-10-01   2.073955   0.000000
88            BJBV__CJ_CZ_CG_EH 2022-11-01   2.160140   2.579761
89            BJBV__CJ_CZ_CG_EH 2022-12-01   2.351649   5.720340
90         BJBV__DG_CF_AF_CG_EH 2022-07-01  10.618871  16.974081
91         BJBV__DG_CF_AF_CG_EH 2022-08-01  11.954071  16.301099
92         BJBV__DG_CF_AF_CG_EH 2022-09-01  12.628453  15.628118
93         BJBV__DG_CF_AF_CG_EH 2022-10-01  11.776929  13.123133
94         BJBV__DG_CF_AF_CG_EH 2022-11-01  10.913980   8.786143
95         BJBV__DG_CF_AF_CG_EH 2022-12-01  12.927461  10.805087
96         BJBW__DG_CF_AF_CG_EH 2022-07-01   0.651282   0.747757
97         BJBW__DG_CF_AF_CG_EH 2022-08-01   0.477566   0.000000
98         BJBW__DG_CF_AF_CG_EH 2022-09-01   0.514294   1.121635
99         BJBW__DG_CF_AF_CG_EH 2022-10-01   0.548537   3.290130
100        BJBW__DG_CF_AF_CG_EH 2022-11-01   0.671311   0.000000
101        BJBW__DG_CF_AF_CG_EH 2022-12-01   0.612530   0.000000
102            NA1__CJ_CZ_CG_EH 2022-07-01   0.098025   0.000000
103            NA1__CJ_CZ_CG_EH 2022-07-01   0.098025   0.209922
104            NA1__CJ_CZ_CG_EH 2022-08-01   0.106205   0.000000
105            NA1__CJ_CZ_CG_EH 2022-08-01   0.106205   0.231305
106            NA1__CJ_CZ_CG_EH 2022-09-01   0.102423   0.000000
107            NA1__CJ_CZ_CG_EH 2022-09-01   0.102423   0.208890
108            NA1__CJ_CZ_CG_EH 2022-10-01   0.081086   0.000000
109            NA1__CJ_CZ_CG_EH 2022-10-01   0.081086   0.204395
110            NA1__CJ_CZ_CG_EH 2022-11-01   0.090426   0.000000
111            NA1__CJ_CZ_CG_EH 2022-11-01   0.090426   0.212800
112            NA1__CJ_CZ_CG_EH 2022-12-01   0.106905   0.000000
113            NA1__CJ_CZ_CG_EH 2022-12-01   0.106905   0.237400
114         NA1__DG_CF_AF_CG_EH 2022-07-01   0.095606   0.000000
115         NA1__DG_CF_AF_CG_EH 2022-07-01   0.095606   0.209922
116         NA1__DG_CF_AF_CG_EH 2022-08-01   0.104839   0.000000
117         NA1__DG_CF_AF_CG_EH 2022-08-01   0.104839   0.231305
118         NA1__DG_CF_AF_CG_EH 2022-09-01   0.106080   0.000000
119         NA1__DG_CF_AF_CG_EH 2022-09-01   0.106080   0.208890
120         NA1__DG_CF_AF_CG_EH 2022-10-01   0.088764   0.000000
121         NA1__DG_CF_AF_CG_EH 2022-10-01   0.088764   0.204395
122         NA1__DG_CF_AF_CG_EH 2022-11-01   0.095533   0.000000
123         NA1__DG_CF_AF_CG_EH 2022-11-01   0.095533   0.212800
124         NA1__DG_CF_AF_CG_EH 2022-12-01   0.104945   0.000000
125         NA1__DG_CF_AF_CG_EH 2022-12-01   0.104945   0.237400
126      YHX__AR_EW_FM_DU_FN_DY 2022-07-01   0.415362   0.394653
127      YHX__AR_EW_FM_DU_FN_DY 2022-08-01   0.457896   0.514516
128      YHX__AR_EW_FM_DU_FN_DY 2022-09-01   0.450536   0.555669
129      YHX__AR_EW_FM_DU_FN_DY 2022-10-01   0.481316   0.614903
130      YHX__AR_EW_FM_DU_FN_DY 2022-11-01   0.539650   0.673301
131      YHX__AR_EW_FM_DU_FN_DY 2022-12-01   0.589879   0.804227

In [250]:
def smape(y_true, y_pred, epsilon=1e-10):
    """
    Calculate the Symmetric Mean Absolute Percentage Error (sMAPE) with handling for zero values.

    Parameters:
    - y_true: Array of true values.
    - y_pred: Array of predicted values.
    - epsilon: Small constant to avoid division by zero.

    Returns:
    - smape: The sMAPE value.
    """
    numerator = np.abs(y_pred - y_true)
    denominator = (np.abs(y_true) + np.abs(y_pred) + epsilon)
    return 100 * np.mean(2 * numerator / denominator)

In [251]:
smape(final_prediction_df['target'],final_prediction_df['mean'])

92.3019664600025